### Product index
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA

### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "name",
     "id": "id",
     "price": "price",
     "image_url": "image_url",
     "description": "description"
}

### Product Update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "title": "Playstation 5"
}

### Product Delete
DELETE http://localhost:3000/products/4

### Supplier Index
GET http://localhost:3000/suppliers

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ben Unell",
  "email": "Bunell@test.com",
  "password": "drowssap123",
  "password_confirmation": "drowssap123"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}