@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgyNDQxNzV9.Fqbcg1mj_7ApD0cTF2dJoecjywSQbohm3l9eh2YZbgo

### Product index
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgxNzM1ODV9._fE4pD0vv4VALNMXpSaE7-1MiJAZ6zJLQFMJdp_bDn0

### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "name",
     "id": "id",
     "price": "price",
     "image_url": "image_url",
     "description": "description"
}

### Product Update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "title": "Playstation 5"
}

### Product Delete
DELETE http://localhost:3000/products/4

### Supplier Index
GET http://localhost:3000/suppliers

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ben Unell",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{

 "product_id": 2,
 "quantity": 10
 
}

### Order index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

### Order show
GET http://localhost:3000/orders/0
Authorization: Bearer {{jwt}}

### Carted Products create
POST http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "user_id": 1,
 "product_id": 2,
 "quantity": 10,
 "order_id": 1, 
 "status": "carted"
 
}

### Carted Products index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}